export const CONTRACT_ADDRESS = (process.env.NEXT_PUBLIC_CONTRACT_ADDRESS?.trim() || '0x0000000000000000000000000000000000000000') as `0x${string}`;

export const MANAGER_ABI = [
  {
    type: 'constructor',
    inputs: [
      { name: '_protocolFeeReceiver', type: 'address', internalType: 'address' },
      { name: '_creatorFeeReceiver', type: 'address', internalType: 'address' },
    ],
    stateMutability: 'nonpayable',
  },
  {
    type: 'receive',
    stateMutability: 'payable',
  },
  // ───────────────────────────── View: Constants ─────────────────────────────
  {
    type: 'function',
    name: 'BUYOUT_FEE_BPS',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'CREATOR_SHARE',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'DEFAULT_TAX_RATE_BPS',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'MULTIPLIER_DENOM',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'ONE_WEEK',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PRICE_COOLDOWN',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'PROTOCOL_SHARE',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'SERVER_FUND_BPS',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'TOTAL_SEATS',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  // ─────────────────────────── View: Seat Queries ────────────────────────────
  {
    type: 'function',
    name: 'getAllSeats',
    inputs: [],
    outputs: [
      {
        name: '',
        type: 'tuple[100]',
        internalType: 'struct ClawSocietyManager.Seat[100]',
        components: [
          { name: 'holder', type: 'address', internalType: 'address' },
          { name: 'price', type: 'uint128', internalType: 'uint128' },
          { name: 'deposit', type: 'uint128', internalType: 'uint128' },
          { name: 'lastTaxTime', type: 'uint64', internalType: 'uint64' },
          { name: 'lastPriceChangeTime', type: 'uint64', internalType: 'uint64' },
          { name: 'buildingType', type: 'uint8', internalType: 'uint8' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'seats',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [
      { name: 'holder', type: 'address', internalType: 'address' },
      { name: 'price', type: 'uint128', internalType: 'uint128' },
      { name: 'deposit', type: 'uint128', internalType: 'uint128' },
      { name: 'lastTaxTime', type: 'uint64', internalType: 'uint64' },
      { name: 'lastPriceChangeTime', type: 'uint64', internalType: 'uint64' },
      { name: 'buildingType', type: 'uint8', internalType: 'uint8' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'accruedTax',
    inputs: [{ name: 'seatId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'depositRunway',
    inputs: [{ name: 'seatId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'getSeatMultiplier',
    inputs: [{ name: 'seatId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'pendingFees',
    inputs: [{ name: 'seatId', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'seatAccumulatedFees',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'seatRewardSnapshot',
    inputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  // ─────────────────────────── View: Global State ────────────────────────────
  {
    type: 'function',
    name: 'serverFundBalance',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'societyAutonomous',
    inputs: [],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'totalActiveWeight',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'globalRewardPerWeight',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'owner',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'protocolFeeReceiver',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'creatorFeeReceiver',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'memeStreamNFT',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'memeStreamTokenId',
    inputs: [],
    outputs: [{ name: '', type: 'uint256', internalType: 'uint256' }],
    stateMutability: 'view',
  },
  // ───────────────────────── Write: Seat Operations ──────────────────────────
  {
    type: 'function',
    name: 'claimSeat',
    inputs: [
      { name: 'seatId', type: 'uint256', internalType: 'uint256' },
      { name: 'price', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'buyoutSeat',
    inputs: [
      { name: 'seatId', type: 'uint256', internalType: 'uint256' },
      { name: 'newPrice', type: 'uint256', internalType: 'uint256' },
      { name: 'maxPrice', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'acquireBatch',
    inputs: [
      {
        name: 'params',
        type: 'tuple[]',
        internalType: 'struct ClawSocietyManager.AcquireParams[]',
        components: [
          { name: 'seatId', type: 'uint256', internalType: 'uint256' },
          { name: 'newPrice', type: 'uint256', internalType: 'uint256' },
          { name: 'maxPrice', type: 'uint256', internalType: 'uint256' },
          { name: 'payment', type: 'uint256', internalType: 'uint256' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'setPrice',
    inputs: [
      { name: 'seatId', type: 'uint256', internalType: 'uint256' },
      { name: 'newPrice', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'addDeposit',
    inputs: [
      { name: 'seatId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'withdrawDeposit',
    inputs: [
      { name: 'seatId', type: 'uint256', internalType: 'uint256' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'abandonSeat',
    inputs: [{ name: 'seatId', type: 'uint256', internalType: 'uint256' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // ────────────────────────── Write: Fee Operations ──────────────────────────
  {
    type: 'function',
    name: 'claimFees',
    inputs: [{ name: 'seatIds', type: 'uint256[]', internalType: 'uint256[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'distributeFees',
    inputs: [],
    outputs: [],
    stateMutability: 'payable',
  },
  {
    type: 'function',
    name: 'pokeTax',
    inputs: [{ name: 'seatIds', type: 'uint256[]', internalType: 'uint256[]' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // ──────────────────────────── Write: Admin ─────────────────────────────────
  {
    type: 'function',
    name: 'transferOwnership',
    inputs: [{ name: 'newOwner', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setProtocolFeeReceiver',
    inputs: [{ name: '_receiver', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setCreatorFeeReceiver',
    inputs: [{ name: '_receiver', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'withdrawServerFund',
    inputs: [
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'onERC721Received',
    inputs: [
      { name: '', type: 'address', internalType: 'address' },
      { name: '', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
      { name: '', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
  // ──────────────────────── Write: External Calls ───────────────────────────
  {
    type: 'function',
    name: 'execute',
    inputs: [
      { name: 'target', type: 'address', internalType: 'address' },
      { name: 'value', type: 'uint256', internalType: 'uint256' },
      { name: 'data', type: 'bytes', internalType: 'bytes' },
    ],
    outputs: [{ name: '', type: 'bytes', internalType: 'bytes' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claimFlaunchFees',
    inputs: [
      { name: 'feeEscrow', type: 'address', internalType: 'address' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'transferERC721',
    inputs: [
      { name: 'nft', type: 'address', internalType: 'address' },
      { name: 'to', type: 'address', internalType: 'address' },
      { name: 'tokenId', type: 'uint256', internalType: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  // ─────────────────────────────── Events ────────────────────────────────────
  {
    type: 'event',
    name: 'SeatClaimed',
    inputs: [
      { name: 'seatId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'holder', type: 'address', indexed: true, internalType: 'address' },
      { name: 'price', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'deposit', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SeatBoughtOut',
    inputs: [
      { name: 'seatId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'newHolder', type: 'address', indexed: true, internalType: 'address' },
      { name: 'oldHolder', type: 'address', indexed: true, internalType: 'address' },
      { name: 'price', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SeatAbandoned',
    inputs: [
      { name: 'seatId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'holder', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SeatForfeited',
    inputs: [
      { name: 'seatId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'holder', type: 'address', indexed: true, internalType: 'address' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PriceChanged',
    inputs: [
      { name: 'seatId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'newPrice', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DepositAdded',
    inputs: [
      { name: 'seatId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'DepositWithdrawn',
    inputs: [
      { name: 'seatId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'TaxCollected',
    inputs: [
      { name: 'seatId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FeesClaimed',
    inputs: [
      { name: 'seatId', type: 'uint256', indexed: true, internalType: 'uint256' },
      { name: 'holder', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'FeesDistributed',
    inputs: [
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ServerFundContribution',
    inputs: [
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'newBalance', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'SocietyAutonomous',
    inputs: [],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'MemeStreamReceived',
    inputs: [
      { name: 'nftContract', type: 'address', indexed: false, internalType: 'address' },
      { name: 'tokenId', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  // ─────────────────────────────── Errors ────────────────────────────────────
  { type: 'error', name: 'InsufficientDeposit', inputs: [] },
  { type: 'error', name: 'InsufficientPayment', inputs: [] },
  { type: 'error', name: 'InvalidSeat', inputs: [] },
  { type: 'error', name: 'NoFeesToClaim', inputs: [] },
  { type: 'error', name: 'NotHolder', inputs: [] },
  { type: 'error', name: 'OnlyOwner', inputs: [] },
  { type: 'error', name: 'PriceCooldown', inputs: [] },
  { type: 'error', name: 'PriceTooLow', inputs: [] },
  { type: 'error', name: 'ReentrancyGuardReentrantCall', inputs: [] },
  { type: 'error', name: 'SeatEmpty', inputs: [] },
  { type: 'error', name: 'SeatOccupied', inputs: [] },
  { type: 'error', name: 'SlippageExceeded', inputs: [] },
  { type: 'error', name: 'TransferFailed', inputs: [] },
  { type: 'error', name: 'ZeroAmount', inputs: [] },
  { type: 'error', name: 'ZeroPrice', inputs: [] },
] as const;
